name: Rust Microservice CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: '1.77.0'

    - name: Build
      run: cargo build --release

    - name: Build Docker image
      run: docker build -t rustactixlogin .

    - name: Push Docker image to registry
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username aaryadesai --password-stdin
        docker tag rustactixlogin aaryadesai/rustactixlogin:latest
        docker push aaryadesai/rustactixlogin:latest
